// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDEzfE-vDZZfN0nCeQa1JTcn9SDici0uU',
    appId: '1:335680820478:android:a35b1e9ecb92efac8981af',
    messagingSenderId: '335680820478',
    projectId: 'quick-delivery-60063',
    storageBucket: 'quick-delivery-60063.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJWfA9Ip65ky_AQzNLJeiQyGBHfz9vpVQ',
    appId: '1:335680820478:ios:f4a177f227a5db0f8981af',
    messagingSenderId: '335680820478',
    projectId: 'quick-delivery-60063',
    storageBucket: 'quick-delivery-60063.appspot.com',
    androidClientId: '335680820478-5n4snl4tmm556c36d19qli7rafqookss.apps.googleusercontent.com',
    iosClientId: '335680820478-2835bl02n0aq1rgg9fnlbmsa1hdlklbp.apps.googleusercontent.com',
    iosBundleId: 'com.quickeats.quickuprider',
  );
}
